import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ReduxProvider } from "./libs/provider/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body className="w-[100vw]" data-new-gr-c-s-check-loaded='14.1237.0' data-gr-ext-installed=''>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
